package oao.oaodemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OAOTestCustomer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Completed Application")
   private java.lang.Boolean complApp;
   @org.kie.api.definition.type.Label(value = "Verified Identity")
   private java.lang.Boolean verifiedID;
   @org.kie.api.definition.type.Label(value = "Agent Approval")
   private java.lang.Boolean agentAppr;
   @org.kie.api.definition.type.Label(value = "Existing Customer")
   private java.lang.Boolean existingCust;
   @org.kie.api.definition.type.Label(value = "Application Type")
   private java.lang.String appType;

   public OAOTestCustomer()
   {
   }

   public java.lang.Boolean getComplApp()
   {
      return this.complApp;
   }

   public void setComplApp(java.lang.Boolean complApp)
   {
      this.complApp = complApp;
   }

   public java.lang.Boolean getVerifiedID()
   {
      return this.verifiedID;
   }

   public void setVerifiedID(java.lang.Boolean verifiedID)
   {
      this.verifiedID = verifiedID;
   }

   public java.lang.Boolean getAgentAppr()
   {
      return this.agentAppr;
   }

   public void setAgentAppr(java.lang.Boolean agentAppr)
   {
      this.agentAppr = agentAppr;
   }

   public java.lang.Boolean getExistingCust()
   {
      return this.existingCust;
   }

   public void setExistingCust(java.lang.Boolean existingCust)
   {
      this.existingCust = existingCust;
   }

   public java.lang.String getAppType()
   {
      return this.appType;
   }

   public void setAppType(java.lang.String appType)
   {
      this.appType = appType;
   }

   public OAOTestCustomer(java.lang.Boolean complApp,
         java.lang.Boolean verifiedID, java.lang.Boolean agentAppr,
         java.lang.Boolean existingCust, java.lang.String appType)
   {
      this.complApp = complApp;
      this.verifiedID = verifiedID;
      this.agentAppr = agentAppr;
      this.existingCust = existingCust;
      this.appType = appType;
   }

}